# Generated by Django 3.0.2 on 2021-01-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='s_password',
            field=models.TextField(default=''),
        ),
    ]
