# Generated by Django 3.0.2 on 2021-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_token',
            },
        ),
    ]
