# Generated by Django 3.0.2 on 2021-01-22 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_tbluser_s_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblteam',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
