# Generated by Django 3.0.2 on 2021-01-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_tbltoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblteam',
            name='members',
            field=models.ManyToManyField(default=None, null=None, to='soccer.TBLMember'),
        ),
    ]
