# Generated by Django 3.0.2 on 2021-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20210122_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblmember',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
